### ISSUE TITLE
Futures

### ISSUE THREAD

**Issue by jack75015** [about14sheep/awsstreaming#1]
Hey :)

First thanks for your very cool job!
I pulled it and it works fine!
Just want to notice some nice futures that could be done:
- adding some logs :)
- navigate in the video (because for the moment, the only possible interaction is play/pause) 

Don't hesitate to update us if you are in to work on it
Great job again! :1st_place_medal:

**Comment by about14sheep** [comment]
Thank you for taking the time to read the article and give feedback on the test program! 

Unfortunately I do not plan on spending any more time on this project. This repo was simply to show how one could use the `SmartStream` class and apply it to HD video. It was not meant to be a legitimate implementation for a video streaming app.

However, feel free to fork the repo and make it your own! I'd be interested to see what people can come up with.

Thank you again

**Comment by japel** [comment]
@jack75015 I was also asking myself how to achieve that, did you come up with something? Or @about14sheep perhaps do you have some rough idea what would be missing to be able to navigate in the video?
